<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
    <PackageReference Include="Veldrid" Version="4.9.1-g3ed7e8fdff" />
    <PackageReference Include="Veldrid.Spirv" Version="1.0.15" />
    <PackageReference Include="Veldrid.ImageSharp" Version="4.9.1-g3ed7e8fdff" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Frinkahedron\Frinkahedron.Core.csproj" />
  </ItemGroup>
</Project>
