<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Frinkahedron.WinUIEditor</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="Controls\VeldridPanel.xaml" />
    <None Remove="Views\GameObjectTemplateView.xaml" />
    <None Remove="Views\RenderableTemplateView.xaml" />
    <None Remove="Views\Shapes\BoxShapeView.xaml" />
    <None Remove="Views\TransformTemplateView.xaml" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\Frinkahedron.TestApp\SceneBuilder_Extensions.cs" Link="SceneBuilder_Extensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Frinkahedron.Veldrid\Frinkahedron.VeldridImplementation.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Page Update="Views\GameObjectTemplateView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
  <ItemGroup>
    <Page Update="Views\RenderableTemplateView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
  <ItemGroup>
    <Page Update="Controls\VeldridPanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Shapes\SphereShapeView.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
  
  <ItemGroup>
    <Page Update="Views\TransformTemplateView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
  <ItemGroup>
    <Page Update="Views\Shapes\BoxShapeView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>